export enum tileState {
    Solid = 1,
    Free = 2,
    Damage = 3,
    soft = 4
}


export let intitialState = {
    gameTime: 0,
    timeLeft: 300000, // at start of the game
    users: [
        {
            userID: "1234", // assigned by us
            userName: 'henk', // provided by sign on
            kills: 0,
            deaths: 0,
            xCoordinates:1, // random assigned by server on sign on
            yCoordinates:1, // random assigned by server on sign on
        },
        {
            userID: "12345",
            userName: 'ingrid',
            kills: 0,
            deaths: 0,
            xCoordinates:38,
            yCoordinates:38,
        },
    ],
    grid: [
        [tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid],
    ]
}