export enum tileState {
    Solid = 1,
    Free = 2,
    Damage = 3,
    soft = 4
}
export const state = {
    gameTime: 0,
    timeLeft: 300000, // at start of the game
    users: [
        {
            userID: 1, // assigned by us
            userName: 'henk', // provided by sign on
            kills: 0,
            deaths: 0,
            xCordinates:1, // random assigned by server on sign on
            yCordinates:1, // random assigned by server on sign on
        },
        {
            userID: 2,
            userName: 'ingrid',
            kills: 0,
            deaths: 0,
            xCordinates:38,
            yCordinates:38,
        },
    ],
    grid: [
        [tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Free,	tileState.Solid],
        [tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid,	tileState.Solid],
    ]
}